### ISSUE TITLE
`cb() never called!` or `Error: Cannot find module 'percy-client'`

### ISSUE THREAD

**Issue by briangonzalez** [percy/percy-js#10] opened 2017-06-29 06:56 UTC

**Comment by briangonzalez** [comment] 2017-06-29 06:56
Cross reference: https://github.com/percy/ember-percy/issues/34

**Comment by jon-hall** [comment] 2017-06-29 11:27
We're also getting this error on doing an `npm install` on various different versions of `node` (4, 6, and 7) and `npm` (3 and 4).

The install ends abruptly with:
```
npm ERR! cb() never called!
```

Eventually tracked it down to `percy-client` being the cause, locking to `percy-client@2.1.0` in our `package.json` fixes the issue.

**Comment by djones** [comment] 2017-06-29 13:34
Hi, just letting you know we're looking into this at the moment and hope to have a fix within a few hours.

**Comment by fotinakis** [comment] 2017-06-29 17:54
Hey @briangonzalez and all, this should be fixed, we had a corrupt npm package and tracked it down. Please upgrade to percy-client 2.1.3!

**Comment by fotinakis** [comment] 2017-06-29 17:54
Also thanks for reporting it!

**Closed by fotinakis** 2017-06-29 17:54 UTC
